# Runs in the internal CI to notify when new definitions released

trigger:
  - master

pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: none
  - script: "echo New Sandbox definitions available"
